export const Chirps = {
  fuckyou: [
    "Fuck you, #Name! Fight me, see what happens.",
    "Fuck you, #Name! Fight me, see what happens.",
    "Fuck you, #Name! Fight me, see what happens.",
    "Fuck you, #Name, your mom molested me two Halloweens ago, shut the fuck up or I’m taking it to Twitter.",
    "Fuck you, #Name, your life is so pathetic I get a charity tax break just by hanging around you!",
    "Fuck you, #Name! Your mom just liked my Instagram post from two years ago in Puerto Vallarta. Tell her I’ll put my swim trunks on for her any time she likes.",
    "Fuck you, #Name, go scoop it off your mom’s floor! She gives my nipples butterfly kisses.",
    "Fuck you, #Name! Your mom tried to stick her finger in my bum, but I said I only let #Name2’s mom do that.",
    "Fuck you, #Name, your mom loves butt play like I love haagan-dazs, let’s get some fuckin’ ice cream.",
    "Fuck you, #Name, your mom ugly cried because she left the lens cap on the camcorder last night. It's fucking amateur hour over there.",
    "Fuck you, #Name. Tell your mom to top up the cell phone she bought me so I can FaceTime her late night.",
    "Fuck you, #Name, I made your mom cum so hard that they made a Canadian heritage minute out of it and Don McKellar played my dick.",
    "Fuck you, #Name, your mom shot cum straight across the room and killed my Siamese fighting fish, threw off the pH levels in my aquarium.",
    "Fuck you, #Name, tell your mom I drained the bank account she set up for me. Top it up so I can get some fucking KFC.",
    "Fuck you, #Name, your breath’s so bad it gave me an existential crisis — it made me question my whole life.",
    "Fuck you, #Name, tell your mom to leave me alone, she’s been laying on my waterbed since Labour Day.",
    "Fuck you, #Name. Shoulda heard your mom last night, she sounded like my great aunt when I pop in for a surprise visit, like, ‘Oooh!’.",
    "Fuck you, #Name. Shoulda heard your mom last night she sounded like a window closing on a tonkanese cats tail like, ‘mmmrrrooowwwwwowowwww!’.",
    "Fuck you, #Name. I made your mom so wet, Trudeau had to deploy a 24-hour infantry unit to stack sandbags around my bed.",
    "Fuck you, #Name. I woke up to your mom ripping dick-dingers off my foreskin, tell her to keep her hands off my scoops.",
    "#Name, I made an oopsie, can you tell your mom to pick up #Name2’s mom on the way over to my place? I double booked them by mistake, you fuckin’ loser.",
    "Fuck you, #Name, tell your mom to give me a timeout. The last time I tried that she threatened to take a header on me into and empty pool at the Quality Suites.",
    "Fuck you, #Name. Your mom sneaky gushed so hard she bucked me off the water bed last night don't tell her I was thinking of #Name2's mom the entire time.",
    "Fuck you, #Name, I talked your mom into a three-way with our midwife and she gassed us both out of the room. I'm fuckin' humiliated!",
    "Fuck you, #Name, your mom wants to name the baby after the place it was conceived. Can't wait to meet Martha's Vineyard Shore.",
    "Fuck you, #Name! Your mom's in her first trimester and already bitching about baby brain. Had to tell her she's been dumber than #Name2's mom since the genesis!",
    "Fuck you, #Name. Your mom got refused entry to that party for coming in blackface, glad I came in blackface before we left her bungalow.",
    "Fuck you, #Name. I dumped your mom and she sent me flowers like I'm a fuckin’ broad!",
    "Fuck you #Name, your mom said she'd do anything to get me back, so I've got her runnin’ around town on my Pokemon Go.",
    "Fuck you #Name. How do you think I feel I gotta fuck you mom one more time because she's still got my Gameboy Color."
  ],
  threethings: [
    "Three things: I hit you, you hit the pavement, and I jerk off on your driver’s side door handle.",
    "Three things: I hit you, you hit the pavement, ambulance hits 60.",
    "Three things: I hit you, you hit the pavement, I fuck your mom again."
  ],
  chirp: [
    "Titfucker.",
    "Give yer balls a tug.",
    "Give yer balls a tug, titfucker.",
    "What the fuck are you looking at, titfucker. Give yer balls a tug.",
    "Fight me, see what happens.",
    "Fight me, see what happens.",
    "Fuck you and your entire fucking life you piece of shit.",
    "Fuck your entire fucking life, bud.",
    "Your life’s so fucking pathetic, I ran a charity 15k to raise awareness for it.",
    "Your life’s so pathetic, I get a Canadian tax credit just for spending time with you, ya fuckin’ loser!",
    "Fuck your whole life and everything in it bud.",
    "Fuck, lemony snicket, what a series of unfortunate events you fuckin’ been through, you ugly fuck.",
    "Fuck my entire fucking life if you titfuckers light a match in here the whole fucking barns going up.",
    "#Name, I made an oopsie, can you tell your mom to pick up #Name2’s mom on the way over to my place? I double booked them by mistake, you fuckin’ loser.",
    "Fuck, you could cut the sexual tension over here with a knife. Give yer balls a tug, titfucker.",
    "https://gfycat.com/snoopywellinformedleech",
    "https://media.giphy.com/media/MEope7bKKdDdFjnlS5/giphy.gif",
    "First puck of the campaign, boys. Fuckin' get involved!",
    "Make yourselves useful, grab me a bag of dill picklers!",
    "The fuck you looking at, ya titfucker? Give yer balls a tug!",
    "Great day for competitive men's hockey, eh. What's women's hockey like? Same things, less competitive or what?"
  ],
  mrhockey: [
    "Suck my Mr. Cocky, ya fucking loser.",
    "Gretz is the best player in the history of the show. Give yer balls a tug.",
    "Gretz holds his share of 61 records in the show, you piece of shit. Don't nickel and dime the Great One!"
  ],
  catcall: [
    "Look at that fucking masterpiece boys.",
    "Who brought the fucking rocket boys?",
    "Look at those legs go up and make a complete fucking ass out of themselves.",
    "Holy fuck would I love to get sticky with #Name.",
    "Fuck #Name looks cold, I'll show her my warm front.",
    "Hey, what's your favorite kind of pizza, Cuteness? Mine's pizza ass.",
    "Hey #Name, you look like that broad from The Hunger Games. I'm gonna call you Cuteness Everdeen. You like edamame?",
  ],
  //TODO add more chirps from the shoresy v girls hocky scenes
  ladychirp: [
    `We should change our Facebook status to "It's complicated".`,
    "You skate like a fuckin' girl, birdcage. No, you're not. Are you really? Holy fuck.",
  ],
}
